[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "application/javascript"
    [build]
  base = "Personal Website"
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "application/javascript"