[build]
  base = "Personal Website"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  CI = "false"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "application/javascript"
